custom_categories:
  - name: Presenting view controller
    children:
    - Present(_:)
    - Present(destination:animated:completion:)
    - Present(viewController:animated:completion:)
  - name: Pushing view controller
    children:
    - Push(_:)
    - Push(destination:animated:completion:)
    - Push(viewController:animated:completion:)
  - name: Adding child view controller
    children:
    - AddChildViewController(_:)
  - name: Dismissing view controller
    children:
    - Dismiss(animated:completion:)
    - Dismiss(viewController:animated:completion:)
  - name: Popping view controller
    children:
    - Pop(animated:completion:)
    - Pop(viewController:animated:completion:)
  - name: Closing view controller
    children:
    - Close(_:_:)
    - Close(_:animated:completion:)
    - Close(_:viewController:animated:completion:)
  - name: Other Navigation Functions
    children:
    - Navigate(_:_:)
  - name: Route Registration
    children:
    - Register(_:)
    - Register(_:patterns:)
  - name: Protocols 
    children:
    - AnyDestination
    - AnyDataReceivable
    - Cacheable
    - DataReceivable
    - Destination
    - Embeddable
    - Matchable
    - Protectable
    - Routable
author: Aron Balog
author_url: https://github.com/aronbalog
theme: jony
